login example
tvd12/ezyfox-examples pull request #1
Opened 2021-08-15 08:18 UTC by namnv11

Login with google example

2021-08-15 08:42 UTC, tvd12 requested changes
@namnv11 PLTA

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/controller/BaseController.java
> +public class BaseController {
lớp này có cần thiết không em? không thì bỏ đi cũng được

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/build.gradle
>  }
thêm 1 dòng trắng ở cuối cho git nó đỡ báo lỗi nhé

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/controller/HomeController.java
> +import org.youngmonkeys.example.ezyhttp.login.service.iplm.UserInformationService;
tên gói bị sai, phải là `impl`

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/controller/LoginController.java
> +        String passHash = EzySHA256.cryptUtfToLowercase(loginRequest.getPassword());
nên là `hashPassword`

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/controller/LoginController.java
> +                    .template("login-err")
viết hẳn là login-error cho nó rõ nghĩa em ạ

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/entity/BaseEntity.java
> +    private Boolean deleted = false;
mặc định nó đã = false rồi em ạ nên bỏ = false đi

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/entity/UserInformation.java
>  }
ditto (nghĩa là comment giống ở trên): thêm 1 dòng trắng

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/repository/AccessTokenRepository.java
> +    @EzyQuery(value = "Select count(e) from AccessToken e Where e.userId = ?0", nativeQuery = true)
mặc định hàm này tự động được tạo query rồi nên em bỏ dòng này đi nhé

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/request/LoginWithGoogleRequest.java
> +public class LoginWithGoogleRequest {
sửa tên các biến theo convention của java nhé, chữ đầu viết thường

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/request/UpdateUserRequest.java
> +    private long Id;
ditto, sửa tên biến

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/request/UpdateUserRequest.java
> +
thừa 1 dòng trắng

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/response/BaseResponse.java
> +    private int Status;
ditto: sửa tên biến

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/response/LoginWithGoogleResponse.java
> +        AccessToken = accessToken;
tương tự sửa tên biến

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/response/LoginWithGoogleResponse.java
> +    public LoginWithGoogleResponse(String accessToken, int status, int errorCode, String errorReason, LocalDateTime responseTime) {
hàm này nhiều tham số quá, xuống dòng kiểu:

```java
public LoginWithGoogleResponse(
	String accessToken, 
	int status, 
	int errorCode, 
	String errorReason, 
	LocalDateTime responseTime) {
```

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/service/IUserInformationService.java
> +public interface IUserInformationService {
mỗi hàm cách nhau 1 dòng trắng cho dễ nhìn em nhé

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/service/iplm/GoogleService.java
> +    private String VerifyUrl;
ditto: sửa tên biến

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/service/iplm/GoogleService.java
> +            ObjectMapper mapper = new ObjectMapper();
đừng tạo `ObjectMapper` nhiều lần, hãy tạo 1 lớp config sau đó tạo bean cho `ObjectMapper` kiểu:

```java
@EzyConfigurationBefore
public class WebAppConfig {
    @EzySingleton
    public ObjectMapper objectMapper() {
      return new ObjectMapperBuilder().build();
    }
}
```

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/service/iplm/GoogleService.java
> +            String response = Request.Post(link)
chỗ này mình có thư viện client cho nó em ạ `ezyhttp-client`

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/service/iplm/UserInformationService.java
> +        AccessToken accessTokenObj = accessTokenRepository.findByField("accessToken", accessToken);
tên biến chỉ cần `accessToken` là đủ rồi em ạ

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/service/iplm/UserInformationService.java
> +        if (accessTokenObj != null && accessTokenObj.getExpireIn().compareTo(LocalDateTime.now()) == 1) {
anh nghĩ logic ở đây là: kiểm tra xem token còn hạn không, vậy chỗ này nên tách thành 2 logic

```java
LocalDateTime now = LocalDateTime.now();
if (accessToken == null ) {
   throw new TokenNotFoundException("token: " + accessToken + " not found");
}
else if (accessToken.getExpireIn().isBeforeNow()) {
   throw new TokenExpiredException("token: " + accessToken + " expired");
}
```

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/service/iplm/UserInformationService.java
> +        if (accessTokenObj != null && accessTokenObj.getExpireIn().compareTo(LocalDateTime.now()) == 1) {
chỗ này mình cần common logic thông qua interceptor em ạ

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/resources/application.yaml
> +  expires_in: 3600
ditto, thêm dòng trắng em ạ

2021-08-15 08:42 UTC, tvd12 commented on ezyhttp-login/src/main/resources/log4j.properties
> +log4j.category.org.hibernate=DEBUG,console
ditto, thêm dòng trắng em ạ

2021-08-15 13:44 UTC, namnv11 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/service/iplm/UserInformationService.java
> +        AccessToken accessTokenObj = accessTokenRepository.findByField("accessToken", accessToken);
do parameter em đang đặt là accessToken nên em đặt tên vậy ạ

2021-08-18 06:22 UTC, tvd12 requested changes

2021-08-18 06:22 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/response/LoginWithGoogleResponse.java
> +    public LoginWithGoogleResponse() {
cái này thừa em ạ, mặc định nó gọi đến super rồi

2021-08-18 06:22 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/response/LoginWithGoogleResponse.java
> +    private String AccessToken;
sửa tên biến cho đúng name convetion

2021-08-18 06:22 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/service/ILoginService.java
> +public interface ILoginService {
Các hàm nên được thêm 1 dòng trắng ở giữ cho dễ nhìn em ạ

2021-08-18 06:22 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/service/impl/GoogleService.java
> +public class GoogleService implements IGoogleService {
sửa lại tên các biến cho đúng naming convention

2021-08-18 06:22 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/service/impl/GoogleService.java
> +/**
comment phải đặt ở trên cùng, trước annotaiton

2021-08-18 06:22 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/service/impl/LoginService.java
> +        return userInformation;
chỗ này có thể return luôn:

```java
return userInformationRepository.findByField("email", email);
```

2021-08-18 06:22 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/service/impl/LoginService.java
> +    public boolean saveUserInformation(UpdateUserRequest request) {
hàm này nên kiểu thế này:

```java
@Override
public void saveUserInformation(UpdateUserRequest request) {
    UserInformation userInformation = userInformationRepository.findById(request.getId());
    if (userInformation == null) {
        throw new UserNotFoundException("user with id: " + request.getId() + " not found");
    }
    userInformation.setFullName(request.getFirstName() + " " + request.getLastName());
    userInformation.setFirstName(request.getFirstName());
    userInformation.setLastName(request.getLastName());
    userInformation.setPassword(EzySHA256.cryptUtfToLowercase(request.getPassword()));
    userInformation.setUpdateTime(LocalDateTime.now());
    userInformationRepository.save(userInformation);
}
```

2021-08-18 06:22 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/service/impl/LoginService.java
> +    public void saveAccessToken(long userId, String accessTokenGoogle) {
Hàm này sẽ chuyển qua lớp `AuthenticationService`

2021-08-18 06:22 UTC, tvd12 commented on ezyhttp-login/src/main/java/org/youngmonkeys/example/ezyhttp/login/service/impl/LoginService.java
> +public class LoginService implements ILoginService {
Lớp này nên đổi tên thành `IUserService` sẽ đúng tên hơn, và nội dung sẽ là:

```java
package org.youngmonkeys.example.ezyhttp.login.service;

import com.google.api.services.oauth2.model.Userinfo;
import org.youngmonkeys.example.ezyhttp.login.entity.UserInformation;
import org.youngmonkeys.example.ezyhttp.login.request.UpdateUserRequest;

public interface IUserService {

    UserInformation getUserInfoByEmail(String email);

    UserInformation getUserById(long userId);

    void saveUserInfoGoogle(Userinfo userinfo, String accessTokenGoogle);

    void saveUserInformation(UpdateUserRequest request);
}
```

2021-08-21 01:31 UTC, tvd12 approved these changes
LGTM

2021-08-21 01:31 UTC, merged